import os
opts = Options('lprof.conf') 
env = Environment(
    ENV = {
      'PATH' : os.environ[ 'PATH' ],
      'HOME' : os.environ[ 'HOME' ], # required for distcc
      'LDFLAGS' : '',
	  'QT_DEBUG': 1
    }, options = opts)

config=env.Configure()
env=config.Finish()
env.Tool('qt', ['$TOOL_PATH'])

src = env.Moc('profilechecker')
print "src",src
lprof = env.Program(target='lprof',source=src)
